local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 15.0
   publish_frequency: 15.0
   
   # resolution of the map in meters per cell
   resolution: 0.02 # see jackal_race.yaml
   
   # do not use static map
   static_map: false
   
   # local map window follows the robot
   rolling_window: true
   
   # size of the local map
   width: 6.0
   height: 6.0
   
