TrajectoryPlannerROS:

  ### Robot Configuration ###
  # achievable velocities
  max_vel_x: 4.0
  min_vel_x: -4.0
  max_vel_theta: 4.0
  min_vel_theta: -4.0
  min_in_place_vel_theta: 0.4
  
  # acceleration limits
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  
  holonomic_robot: false
  
  ### Goal Tolerance ###
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  
  ### Forward Simulation Parameters ###
  # amount of time to forward-simulate trajectories, in seconds
  sim_time: 10.0
  
  # step sizes to take on a given trajectory
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  
  # number of samples to use when exploring velocity space
  vx_samples: 3
  vtheta_samples: 20

  # controller frequency
  controller_frequency: 15.0
  
  ## Trajectory Scoring Parameters ##
  # distances are expressed in meters
  meter_scoring: true
  
  # weights for scaling
  pdist_scale: 1.8
  gdist_scale: 0.6
  occdist_scale: 0.01
