global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 15.0
   publish_frequency: 15.0
   
   # resolution of the map in meters per cell
   resolution: 0.02 # see jackal_race.yaml
   
   # use static map provided by the map server
   static_map: true
   
   # global map window does not follow the robot
   rolling_window: false
